### PR TITLE
Added local lyrics with .lrc and Sync for lyrics

### PR DESCRIPTION
**Pull request by lecheel**
lrc support sync with timestamp
Screenshot from 2024-11-25 20-51-02

### CODE REVIEW

**Comment by lecheel** [comment]
Done

**Review by lecheel — COMMENTED** [review]
done

**Review by lecheel — COMMENTED** [review]
monkey test done

**Comment by Jugran** [comment]
Thank you for contributing to this project. I will review the changes and merge.

**Comment by Jugran** [comment]
Looks like only reading of lrc files is supported and not fetching from lrclib.net.
I will be merging this to development branch for now and I will be lrclib as a new source for auto loading of synced lyrics.

**Comment by lecheel** [comment]
which retrive the local xxx_song.lrc for lyrics sync

**Pull request merged**
